version: '3.8'

services:
  transactions_enricher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=app
    ports:
      - "${PORT:-5001}:5001"
    networks:
      - enricher_network

networks:
  enricher_network:
    driver: bridge
